spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/instagram?currentSchema=instagram
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

  mail:
    host: sandbox.smtp.mailtrap.io
    username: 7d2580a8555928
    password: 9b3d209d448b5b
    port: 587
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  freemarker:
    template-loader-path: classpath:/
---

server:
  port: 8081
springdoc:
  api-docs:
    path: /api-docs


jwt:
  access:
    token:
      expiry: 600000 # 10 minutes
      secret:
        key: 357638792F423F4528482B4D6250655368566D597133743677397A24432646294A404E635266546A576E5A7234753778214125442A472D4B6150645367566B58
  refresh:
    token:
      expiry: 864000000 # 10 days
      secret:
        key: 7134743777217A25432A462D4A614E645267556B58703272357538782F413F44
